### ISSUE TITLE
Make system changes to allow for easier packaging

### ISSUE THREAD

**Issue by x49** [groops-devs/groops#1]
I'm in the process for creating a `PKGBUILD` to allow for seamless installation of groops and the groops-gui on Arch Linux. This necessitates that the groops and groopsMPI binaries be marked as installation targets in the CMake configuration (see [here](https://github.com/x49/groops/commit/55a6c540ac4f8c44512d52f03dc13250d69ffadc)), so that they can end up in `/usr/bin`.

Would be my honor to open PR #1 if that's something you guys would like having :)

Things I'd like to address in that:
 1) The above `cmake` fix.
 2) Referencing the `PKGBUILD` which I'll host on the arch user repository in the installation instructions.

Cheers,
Matthias

**Comment by akvas** [comment]
Hey Matthias,

sounds good, go ahead and create the PR!

Cheers,
Andreas
