### ISSUE TITLE
Missing thermosphere dataset/folder

### ISSUE THREAD

**Issue by bedbug6404** [groops-devs/groops#10]
Hi,

Sorry I felt that I am so annoying and did my third issue, lol. But for example three of 'data handling', _atmosphericDrag_ require input from the 'thermosphere' folder. This folder is not yet in the  [ftp data folder](https://ftp.tugraz.at/outgoing/ITSG/groops/data/)

**Comment by sestras** [comment]
Hi,

Thanks for notifying us about this. The thermosphere folder is now available on the FTP server and will be updated regularly.
