### ISSUE TITLE
Some questions of config files.

### ISSUE THREAD

**Issue by FFFFFG-IGG** [groops-devs/groops#12]
Dear developer,
I am a new window user of groops , and have read the documents in https://groops-devs.github.io/groops/html/general.configFiles.html. I am confused and have following questions:
1.Commends like " groops --xsd groops.xsd" can be  run in which place?
![image](https://user-images.githubusercontent.com/59271400/125771231-ea77b0d8-2d56-41cb-a2ec-34d8e4858ed6.png)
2.How to create a config file, should I create a xsd file completely, or there may be a template that we just need put in some parameters?
I'll be appreciate if there are some examples about config files! And thanks for the open source code！
best wishes！

**Comment by sestras** [comment]
Hello,

1) If you have followed the [Windows post-installation steps](https://github.com/groops-devs/groops/issues/5#issuecomment-809380856) in the Installation Guide, the path to groops.exe should be included in your environment and you should be able to run groops.exe anywhere in your command line interface (e.g., cmd.exe). In any case, groops.exe should be located in <your GROOPS directory>\bin. You can also run GROOPS directly from the GUI (see below).

2) The XML schema (XSD) file groops.xsd is already part of the repository and should be located in your GROOPS directory. You only have to recreate the XSD file in case you modify the source code. You can use the GROOPS GUI to create config files. As you are on Windows, you can install the GUI from the installer attached to each [release](https://github.com/groops-devs/groops/releases). The documentation features a section about [using the GUI](https://groops-devs.github.io/groops/html/general.gui.html). You can find an example config file attached to https://github.com/groops-devs/groops/issues/5#issuecomment-809380856 which you can use to test your installation. We are planning to provide more example config file in the future, until then you can use the cookbook examples listed in the documentation to get to know some features of GROOPS.

Hope this helps!

**Comment by FFFFFG-IGG** [comment]
Thanks for your tips, it's useful!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "groops-devs/groops"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 晚上11:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [groops-devs/groops] Some questions of config files. (#12)





 
Hello,
  
 
If you have followed the Windows post-installation steps in the Installation Guide, the path to groops.exe should be included in your environment and you should be able to run groops.exe anywhere in your command line interface (e.g., cmd.exe). In any case, groops.exe should be located in \bin. You can also run GROOPS directly from the GUI (see below).
 
 
 
The XML schema (XSD) file groops.xsd is already part of the repository and should be located in your GROOPS directory. You only have to recreate the XSD file in case you modify the source code. You can use the GROOPS GUI to create config files. As you are on Windows, you can install the GUI from the installer attached to each release. The documentation features a section about using the GUI. You can find an example config file attached to #5 (comment) which you can use to test your installation. We are planning to provide more example config file in the future, until then you can use the cookbook examples listed in the documentation to get to know some features of GROOPS.
 
  
Hope this helps!
