### ISSUE TITLE
'groops.exe' is not an internal or external command, nor is it an executable program or batch file.

### ISSUE THREAD

**Issue by FFFFFG-IGG** [groops-devs/groops#13]
Dear developer:
When I get start in groops, it doesn't work and the terminal shows " 'groops.exe' is not an internal or external command, nor is it an executable program or batch file.", (I've followed the installation of groops in https://github.com/groops devs/groops/blob/main/INSTALL.md#microsoft-windows), then I add the path of "groops.exe" into the path environment and solve it sucessfully. I notice that "add the path of "groops.exe" into the path environment" is not mentioned in the "installation", I wonder if there is a omission in "installation" or there is something wrong in my  installation process.
best wishes!

**Comment by sestras** [comment]
Hello,

the [Windows post-installation steps](https://github.com/groops-devs/groops/blob/main/INSTALL.md#windows-post-installation-steps) in the Installation Guide explain how to add the relevant paths to your environment. This has been tested on several Windows 10 machines. Thus, I have to assume something went wrong when you performed these steps. As it is not a GROOPS-specific problem but rather Windows-related, I unfortunately cannot help you any further. If you have trouble with the post-installation steps, you can find numerous guides on adding paths to the Windows environment online.

Best regards,
Sebastian
