### ISSUE TITLE
About oceanPoleTide

### ISSUE THREAD

**Issue by FFFFFG-IGG** [groops-devs/groops#14]
Hello Developer,
When I get start in 'Orbit integration', I am confused with some data, such as secularPole2018.xml and meanPole2010.xml in processing oceanPoleTide, what the difference? Or using either of them are reasonable? 
By the way, are the default inputfile is correct when I get start in this sector ?(circled in following pictures)
![image](https://user-images.githubusercontent.com/59271400/127793603-6fe45e98-7663-4289-af6f-cfb27e1d5212.png)
Looking forward to hearing from you!

**Comment by sestras** [comment]
Hello,

secularPole2018.xml is the new linear mean pole adopted by the IERS that replaces the previous mean pole representation. For more information, please check the updated IERS conventions (https://iers-conventions.obspm.fr/content/chapter7/icc7.pdf) or related scientific publications, for example https://repositories.lib.utexas.edu/bitstream/handle/2152/75555/Ries_Desai_AGU2017.pdf?sequence=3.

You usually want to use the default input files. In many cases, such as the one you showed, the option to change it is only there in case you want to do specific investigations with a different model.

**Comment by FFFFFG-IGG** [comment]
Dear Mr.Sebastian
&nbsp; There are some problems during&nbsp;&nbsp;the&nbsp;GNSS precise point positioning (PPP) program which confused me a lot:
1.Integration&nbsp;
&nbsp; &nbsp;When I prepared all the forces mentioned in the document of&nbsp;GNSS precise point positioning (PPP) and obtained the&nbsp;integrated orbit from 'PreprocessingVariationalEquation',&nbsp; there comes a big difference between the resampled orbit and the integrated orbit, which are shown in following figure. (Figure 1 represents resampled orbit, Figure 2represents integration)&nbsp;

Figure 1





Figure 2


As the figures shown above, I wonder whether the situation is normal in the integtation step, or there may be somthing wrong in my processing(e.g doc prepartion).


&nbsp;2. Orbit fit
The fit procedure can be divided in two step as introducing in 'ppp doc', in the first step I fit the integrated orbit to resempled orbit by estimating solar pressure radiation and get the fitted orbit below:



The fitted orbit is still largely different from resampled orbit, is this normal?
In the second step I fit the orbit again with stochastic pulse and get the following orbit:

The twice fitted orbit seems similar to the resampled orbit, and here comes some question in summary:
1. Is the large difference in the integration and the first step in orbit fit normal?
2. How can I evaluate the results?(Which parameters in the reslut document can reflect the precision of the integrated orbit?)
3. If there are some examples in ppp, would you mind share it with me?


I am very appreciate to your kind reply for my question before. As I am a freshman in GNSS and groops, I often get confused during
the study, but I'm still interested in this field and the software 'GROOPS' , I hope to keep contact with you developers and learn more from you!I'm looking forward to your reply!


Kind regards.
Yongzhao Fan




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "groops-devs/groops"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月3日(星期二) 晚上9:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [groops-devs/groops] About oceanPoleTide (#14)





 
Hello,
 
secularPole2018.xml is the new linear mean pole adopted by the IERS that replaces the previous mean pole representation. For more information, please check the updated IERS conventions (https://iers-conventions.obspm.fr/content/chapter7/icc7.pdf) or related scientific publications, for example https://repositories.lib.utexas.edu/bitstream/handle/2152/75555/Ries_Desai_AGU2017.pdf?sequence=3.
 
You usually want to use the default input files. In many cases, such as the one you showed, the option to change it is only there in case you want to do specific investigations with a different model.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sestras** [comment]
Hello,

Release [2021-09-06](https://github.com/groops-devs/groops/releases/tag/2021-09-06) features a redesign of the GNSS processing interface to make usage a little bit easier and more flexible. In addition, we now provide GNSS [example scenarios](https://ftp.tugraz.at/outgoing/ITSG/groops/scenario/) with config files and data. Since the structure of the [GNSS-related GROOPS data and metadata](https://ftp.tugraz.at/outgoing/ITSG/groops/data/gnss/) has changed, we recommend to download the latest version. More information can be found in the updated [cookbooks and documentation](https://groops-devs.github.io/groops/html/index.html).

PPP now is much simpler and the orbit integration step is not necessary anymore. Please check out the example scenario linked above as well as the updated cookbook on PPP. Hope this helps.
