### ISSUE TITLE
GUI CODE ERROR

### ISSUE THREAD

**Issue by zdwangjian5** [groops-devs/groops#174]
### Description

 optional element can not be deleted.
![image](https://user-images.githubusercontent.com/101688056/227861914-91727b91-1202-4175-8ca8-6446f2f68a7f.png)

### GROOPS version

main (latest commit)

### Operating systems

- [ ] Linux
- [X] Windows
- [ ] macOS
- [ ] Other (please specify in the description)

**Comment by zhedumi** [comment]
Hi,

That is not a bug. It  was designed like this on purpose.  


Best regards,
Patrick
