### ISSUE TITLE
windows10 install

### ISSUE THREAD

**Issue by MrSoul8715** [groops-devs/groops#19]
Hello developers, when I install GROOPS on windows10 following the Microsoft Windows installation instruction. I got a lots of error when  compile GROOPS with "mingw32-make.exe -j4".
Administrator@PC-20200908CBNV MINGW64 /c/groops/source/build
# mingw32-make.exe -j4
Consolidate compiler generated dependencies of target groopscore
[  0%] Building Fortran object CMakeFiles/groopscore.dir/external/nrlmsis2/msis_gfn.F90.obj
[  0%] Building CXX object CMakeFiles/groopscore.dir/base/constants.cpp.obj
[  0%] Building CXX object CMakeFiles/groopscore.dir/base/doodson.cpp.obj
[  0%] Building CXX object CMakeFiles/groopscore.dir/base/ellipsoid.cpp.obj
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/sec_api/stdlib_s.h:9,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/stdlib.h:765,
                 from C:/msys64/mingw64/include/c++/10.3.0/bits/std_abs.h:38,
                 from C:/msys64/mingw64/include/c++/10.3.0/cmath:47,
                 from C:/groops/source/base/importStd.h:17,
                 from C:\groops\source\base\constants.cpp:16:
C:/msys64/usr/include/stdlib.h:39:3: error: conflicting declaration 'typedef struct div_t div_t'
   39 | } div_t;
      |   ^~~~~
In file included from C:/msys64/mingw64/include/c++/10.3.0/bits/std_abs.h:38,
                 from C:/msys64/mingw64/include/c++/10.3.0/cmath:47,
                 from C:/groops/source/base/importStd.h:17,
                 from C:\groops\source\base\constants.cpp:16:
C:/msys64/mingw64/x86_64-w64-mingw32/include/stdlib.h:63:5: note: previous declaration as 'typedef struct _div_t div_t'
   63 |   } div_t;
      |     ^~~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/sec_api/stdlib_s.h:9,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/stdlib.h:765,
                 from C:/msys64/mingw64/include/c++/10.3.0/bits/std_abs.h:38,
                 from C:/msys64/mingw64/include/c++/10.3.0/cmath:47,
                 from C:/groops/source/base/importStd.h:17,
                 from C:\groops\source\base\constants.cpp:16:
C:/msys64/usr/include/stdlib.h:45:3: error: conflicting declaration 'typedef struct ldiv_t ldiv_t'
   45 | } ldiv_t;
      |   ^~~~~~
In file included from C:/msys64/mingw64/include/c++/10.3.0/bits/std_abs.h:38,
                 from C:/msys64/mingw64/include/c++/10.3.0/cmath:47,
                 from C:/groops/source/base/importStd.h:17,
                 from C:\groops\source\base\constants.cpp:16:
C:/msys64/mingw64/x86_64-w64-mingw32/include/stdlib.h:68:5: note: previous declaration as 'typedef struct _ldiv_t ldiv_t'
   68 |   } ldiv_t;
      |     ^~~~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/sec_api/stdlib_s.h:9,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/stdlib.h:765,
                 from C:/msys64/mingw64/include/c++/10.3.0/bits/std_abs.h:38,
                 from C:/msys64/mingw64/include/c++/10.3.0/cmath:47,
                 from C:/groops/source/base/importStd.h:17,
                 from C:\groops\source\base\constants.cpp:16:
C:/msys64/usr/include/stdlib.h:52:3: error: conflicting declaration 'typedef struct lldiv_t lldiv_t'
   52 | } lldiv_t;
      |   ^~~~~~~
......
How can I fix these errors?
 Looking forward to your reply. Many thanks !

**Comment by akvas** [comment]
Hi!

It seems that your MSYS2 setup is mixed up. The compiler has both the MSYS2 base and MinGW64 include directories in its search path (i.e. C:/msys64/mingw64/x86_64-w64-mingw32/include/ and C:/msys64/usr/include/). I was not able to reproduce this behavior with a fresh install of MSYS2 v20210725.

This is not a GROOPS issue, so the only thing I can recommend is to reinstall MSYS2 from scratch.

Cheers,
Andreas
