### ISSUE TITLE
Is there relative positioning in GROOPS?

### ISSUE THREAD

**Issue by FFFFFG-IGG** [groops-devs/groops#20]
Hellow developers, I'd like to get some relative positioning results through 'groops', and I do not find some doc of it, so I wonder if there is any relative postioning program in groops? Many thanks!

**Comment by sestras** [comment]
Hello,

GNSS processing in GROOPS is based on the raw observation approach and thus does not use any observation differences or relative parametrizations between receivers. You will always get absolute coordinates out of the program GnssProcessing, even in case of network solutions. There is no program specifically for relative positioning.
