### ISSUE TITLE
Error running sample

### ISSUE THREAD

**Issue by Yaopeng634** [groops-devs/groops#217]
### Description

When running the example in the second video tutorial, I encountered the following error. Why did this error occur?
![LX9BK3UYLA(XV7%XLX`UT 0](https://github.com/groops-devs/groops/assets/146629001/7a257a22-d463-45b1-b92d-8763724cef1b)

### GROOPS version

main (latest commit)

### Operating systems

- [ ] Linux
- [X] Windows
- [ ] macOS
- [ ] Other (please specify in the description)

### Log output

```dircolors
=== Starting GROOPS ===
Config file: <C:/groops/data/scenario/orbit/02groopsSimulateOrbit.xml>
****** Error ******
in C:\groops\source\config\config.cpp:115 (Config)
in C:\groops\source\parser\xml.cpp:223 (read)
Parser Error in row 6, column 37: not well-formed (invalid token)
=== Finished GROOPS with error ===

C:\groops\data\scenario\orbit>
```

**Comment by tmayerguerr** [comment]
Hi,

Your `02groopsSimulateOrbit.xml` seems to contain something that is not compatible with the XML standard. Please open the file with a text editor and take a look at row 6, column 37. If you do not find the problem, please provide us the file `02groopsSimulateOrbit.xml` and we try to find the error.

regards
Torsten

**Comment by Yaopeng634** [comment]
Hi developer, sorry to bother you again, as a beginner in GROOPS, when I want to debug GROOPS using VS code, I get the following error in program.h, however, it doesn't show up in program.cpp, what should I do to avoid this error?
