### ISSUE TITLE
[GenericMappingTools/gmt#7856] Creation of colobar fails for small increments

### ISSUE THREAD

**Issue by zinphi** [groops-devs/groops#218]
### Description

FYI: there is an issue within GMT (6.4.0) that impacts PlotMap and maybe other GROOPS plotting routines. For further information, please refer to:
# GenericMappingTools/gmt#7856

### GROOPS version

main (latest commit)

### Operating systems

- [X] Linux
- [X] Windows
- [X] macOS
- [X] Other (please specify in the description)

**Comment by zinphi** [comment]
There is already a fix underway which will (probably) be delivered with the next GMT release: 
https://github.com/GenericMappingTools/gmt/commit/1132cc6563780757c0a8b9858af43161315f0c6b
So, once available, please update GMT if you are affected by this issue.

**Comment by tmayerguerr** [comment]
Closed, as this is not a GROOPS bug. 

By the way, maybe it is better to adjust the units in [PlotMap](https://groops-devs.github.io/groops/html/PlotMap.html) or similar to get readable labels in the plots (for example (`value=1e9*data0`) for nm/s^2 instead of m/s^2).

Torsten
