### ISSUE TITLE
Question about "derivative()" method in class "ExpressionSqrt"

### ISSUE THREAD

**Issue by MrSoul8715** [groops-devs/groops#246]
Hi, I've meet some problem when reading code "derivative()" in file "expressionParser.cpp".  In this method, the statement "_return operand->derivative(var)/sqrt(operand->clone());_" seems to be wrong.  The correct way maybe "**return operand->derivative(var)/ (exprValue(2.0)*sqrt(operand->clone()));**". Thanks for reading.

**Comment by tmayerguerr** [comment]
Hi,
You are right. We fixed the bug. Thanks for your help.
Best regards
Torsten
