### ISSUE TITLE
Error dynamic link library

### ISSUE THREAD

**Issue by gnssgrid** [groops-devs/groops#250]
### Description

Hi. After a successful installation (without errors), when I try to start Groops, I get an error message saying 'The procedure entry point DllMain could not be located in the dynamic link library C:\msys64\mingw64\bin\libidn2-0.dll'. Steps after installation are performed, and variables are added to path. How can I resolve this?
OS is Windows 11 Pro
![error](https://github.com/groops-devs/groops/assets/34404011/68508201-70d2-4402-a6eb-e487218c5b66)

### GROOPS version

main (latest commit)

### Operating systems

- [ ] Linux
- [X] Windows
- [ ] macOS
- [ ] Other (please specify in the description)

**Comment by gnssgrid** [comment]
Solution is to move the PATH entry for C:\msys64\mingw64\bin to first in the list. 
https://stackoverflow.com/questions/73226740/libcurl-get-in-mem-example-exe-only-runs-in-mingw64-bin-folder

**Comment by tmayerguerr** [comment]
Hi Dzevad,

We knew that this problem sometimes occurs, but so far we have not had a solution. Thank you for your solution. We have included a note in the installation instructions.

best regards
Torsten
