### ISSUE TITLE
Question about function "void fillSymmetric(MatrixSliceRef A)"

### ISSUE THREAD

**Issue by MrSoul8715** [groops-devs/groops#253]
The test condition "i < A.rows()" in the for loop seems to be wrong. The correct test condition may be "i < A.rows()-1". Thanks for reading.

**Comment by tmayerguerr** [comment]
Hi, 
You are only partly right: the last loop is indeed not necessary, but does not cause any problems as the zero size copy does nothing.
regards
Torsten
