### ISSUE TITLE
Simulation of GNSS measurements

### ISSUE THREAD

**Issue by Liquid87** [groops-devs/groops#27]
Hello,

I am trying to use the program GnssSimulateReceiver to simulate some observation data for a Galileo constellation. When I execute my config file (attached), the program outputs the following lines:

=== Starting GROOPS ===
Config file: <010groopsSimulate.xml>
--- LoopPrograms (daily) ---
Run programs
=== 1. loop ===
  1 of 1 (time: 00:00:00, remaining: 00:00:00)
--- GnssSimulateReceiver ---
Init GNSS
init transmitters
Unable to read orbit file <data/orbit/orbit_2020-01-01.E20.dat>, disabling transmitter.
Unable to read orbit file <data/orbit/orbit_2020-01-01.E22.dat>, disabling transmitter.
Unable to read orbit file <data/orbit/orbit_2020-01-01.E51.dat>, disabling transmitter.
Unable to read orbit file <data/orbit/orbit_2020-01-01.E52.dat>, disabling transmitter.
init station network
read observations
  69 of 69 (time: 00:00:00, remaining: 00:00:00)
  69 of 69 stations used
compute tides & loading
simulate observations
  69 of 69 (time: 00:01:03, remaining: 00:00:00)
  transmitter: 24
  receiver:    0
2020-01-01_00-00-00 - 2020-01-02_00-00-00: no useable receivers
  1 of 1 (time: 00:01:05, remaining: 00:00:00)
=== Finished GROOPS ===

The file is configured to run on the cookbook provided for the GNSS satellite orbit determination and station network analysis using the same config files as for this example. Can you please let me know if there is something wrong in my configuration file ?

Thanks in advance
Jordi
[Simulate.txt](https://github.com/groops-devs/groops/files/7635819/Simulate.txt)

**Comment by tmayerguerr** [comment]
Dear Jordi,

The standard preprocessing checks are performed after the simulation.
Our approach needs at least two code and phase observations at two different frequencies,
therefore all single frequency observation/epochs are dropped.
Solution: simulate at least the observationTypes: C1CE, L1CE, L5QE, C5Q, ...

We will implement in future more detailed information which and why observations are removed during preprocessing. At the moment it is impossible to see why receivers are disabled.

regards
Torsten

**Comment by Liquid87** [comment]
Dear Torsten,

And additional question, is there any way to impose code and signal biases ? I do not see how can I control these values in the simulation.

Regards
Jordi

**Comment by tmayerguerr** [comment]
Dear Jordi,

The standard preprocessing checks are performed after the simulation.
Our approach needs at least two code and phase observations at two different frequencies,
therefore all single frequency observation/epochs are dropped.
Solution: simulate at least the observationTypes: C1CE, L1CE, L5QE, C5Q, ...

We will implement in future more detailed information which and why observations are removed during preprocessing. At the moment it is impossible to see why receivers are disabled.

regards
Torsten

**Comment by tmayerguerr** [comment]
> And additional question, is there any way to impose code and signal biases ? 

Add Parametrization->SignalBiases and with inputfileSignalBiasReceiver/Transmitter 
you can provide a file for each receiver/transmitter in the [signalBias file format](https://groops-devs.github.io/groops/html/fileFormat_gnssSignalBias.html).
