### ISSUE TITLE
Some Questions for GROOPS-PPP

### ISSUE THREAD

**Issue by FFFFFG-IGG** [groops-devs/groops#28]
Hellow developers:
  How are you doing?
  Recently, I have some questions for GROOPS-PPP and find them difficult to solve, they can be concluded in:
   1. Results of PPP using TUG's product (clock, sp3, signalBias) differ largely from using other AC's products
![image](https://user-images.githubusercontent.com/59271400/145541053-063232b7-2f0a-4cd8-a359-75618222cba1.png)
                                                   (a)    
![image](https://user-images.githubusercontent.com/59271400/145541307-a4ba665b-60c7-4bbe-a6f4-1761b3b4c297.png)
                                                   (b)
Figure 1. PPP results of BJFS(2020-01-01) using TUG's products and other AC's products.
(a)results using TUG's products. (b) result using GRG's clock,sp3 and CNT's signal bias.(Date is wrong in b, it should be 2020-01-01)

![image](https://user-images.githubusercontent.com/59271400/145541149-a8400adb-af9e-4b01-8436-b35426306e36.png)
                                                  (a) 
![image](https://user-images.githubusercontent.com/59271400/145541170-961f25d5-8e10-4971-9a3e-ffdb92aaede8.png)
                                                  (b)
Figure 2. PPP results of GRAZ using TUG's products and other AC's products, date:2020-01-01.
(a)results using TUG's products. (b) result using GRG's clock,sp3 and CNT's signal bias.

  Apparently, when other AC's products are used, the ppp result is awful. For finding the cause, I
have also used different AC'S products to implement ppp of various station in different date with
groops, but they all lead to the unpleasant results. I'm socked and hope for your suggestions!
 
2. About the example xml 'plot'.

![image](https://user-images.githubusercontent.com/59271400/145541204-8c567281-97ca-4a9d-a950-22699aba1acb.png)
Figure 3. Plot of station position.

  As demonstrated in 'groopsPlot.xml', these lines (red, blue and green) are computed by '100(position-mean(position))'.
What does it means? I guess they represent precision of position, if so, the positions of station are seen as dynamic that
are different between epochs, useing position-mean(position) seems not plausible. Would you mind to explain it?

  If available, would you like to give me some adviceabout the above question?

**Comment by sestras** [comment]
Hello,

It is hard to answer your questions without more information about your processing. Here are some questions that might help you figure out what is happening on your own, and you don't have to provide answers here.

- Which GNSS constellations are you using?
- Are the CNT signal biases consistent with the GRG orbits and clocks? I don't know anything about these bias products.
- Does CNT provide observable-specific signal biases? How did you convert them to the GROOPS signal bias format?
- Do they provide both code and phase biases? 
- Do the provided biases cover all signal types you are using?
- Are you resolving the ambiguities to integer values?
- Have you tried using the TUG signal biases with the GRG orbits and clocks or the CNT signal biases with the TUG orbits and clocks? They won't be consistent, but it will give you an idea of the magnitude of error you will get from possible inconsistencies. And you might see which product causes the issues.

I have not tried using signal biases from other analysis centers myself, so I cannot tell you what specifically might cause your problem.

Regarding your second question, the config file uses "100*(data2-data2median)". Here, data2 is the second data column of the input file. This file contains one row per epoch. data2median is the median value over all rows for this column (see [documentation](https://groops-devs.github.io/groops/html/general.parser.html)). In this case, it means the median over the time series is removed from the data and the data is then multiplied by 100 to convert from meters to centimeters.

Hope this helps,
Sebastian
