### ISSUE TITLE
official debian package, license problem

### ISSUE THREAD

**Issue by alexmyczko** [groops-devs/groops#29]
Trying to create an official package, I encounter many typos, listed here:

https://mentors.debian.net/package/groops/

you might want to fix them?

err figured it can't be distributed commercial, it can't be changed (the parts in source/external)... giving up on an official package

**Comment by sestras** [comment]
The typos should be fixed with cf59ec6, thanks for notifying us about them.

**Comment by alexmyczko** [comment]
thanks. is there a chance to change the licensing for the fortran files or replace them with some dfsg compliant license?

**Comment by tmayerguerr** [comment]
We have tried to reduce the dependencies on external sources as much as possible. The remaining Fortran sources are implementations of specific geopyhsical models and I don't know how to change the license or replace them.

It should be possible to modify GROOPS so that it can be compiled without these models and with reduced functionality. We did similar for some external libraries (Z library, netcdf, erfa) by using #ifdefs in the code, see CMakeLists.txt. I can take a look at it, but definitely not this month. Could this be a way?

regards
Torsten

**Comment by alexmyczko** [comment]
Hmm, it's about these files:

```
Files: source/external/hwm/*
Copyright: 2014 Douglas Drob <douglas.drob@nrl.navy.mil>
           2008 John Emmert
                Geospace Science and Technology Branch
                Space Science Division, Naval Research Laboratory
                4555 Overlook Ave., Washington, DC 20375
License: CC-BY-NC-ND-4.0
 See https://creativecommons.org/licenses/by-nc-nd/4.0
```

and 

```
Files: source/external/jb2008
Copyright: 2008 Jacchia & Bruce R Bowman
License: Space-Environment-Technologies-License
 See http://sol.spacenvironment.net/jb2008/License.html
```

I thought maybe they could be contacted and asked nicely? I'm not sure if the software is still useful removing those specific geophysical models.

**Comment by tmayerguerr** [comment]
We added the option in CMake to disable some part of the sources, see at the end of [INSTALL.md](https://github.com/groops-devs/groops/blob/main/INSTALL.md).

The mentioned models HWM and JB2008 are only used for drag modelling for LEO satellites not equipped with an accelerometer. Therefore GNSS processing as well as GRACE/GRACE-FO gravity field processing is fully working without using these models.

Additionally, GROOPS includes two alternative thermospheric models with JB2008 and NRLMSIS. So removing one causes no problems as you can use the other one. The thermospheric wind model HWM14 has only minor impact of the drag modelling and also can be left out easily.

**Comment by alexmyczko** [comment]
I'm failing to build with: https://sid.ethz.ch/debian/groops/2022/groops_0%2Bgit20220120%2Bds-1_amd64.build

**Comment by akvas** [comment]
Hi Alex,

the header ```external/hwm/hwm.h``` is one of our files (and hence GPLv3), so you do not have to delete it. For a list of files in ```external/``` with non-compatible licenses please check out the corresponding [README](https://github.com/groops-devs/groops/blob/main/source/external/README.md).

Best regards,
Andreas

**Comment by alexmyczko** [comment]
many thanks :)

**Comment by alexmyczko** [comment]
just to keep this visible and public, if someone else wants to pick it up:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1001622

**Comment by alexmyczko** [comment]
so i tried to get groops into non-free, but msis is a problem with:

A user of the Software shall not: (...) (iii) disseminate the Software (...)

can groops still be useful without msis?

**Comment by tmayerguerr** [comment]
Hi Alex,
msis is a thermospheric model and is used to calculate atmospheric drag for low earth orbit (LEO) satellites. It is not needed for full GNSS processing (GNSS satellites orbit outside the thermosphere). GRACE satellites are equipped with an accelerometer and measure atmospheric drag directly. So all important applications work without a thermospheric model.
regards
Torsten

**Comment by alexmyczko** [comment]
That is great to know, another chance to get groops easily be installed with apt…

**Comment by alexmyczko** [comment]
Can we get a switch like DISABLE_NRLMSIS2=TRUE  where groops builds without source/external/nrlmsis2 ?

**Comment by tmayerguerr** [comment]
Have I misunderstood something or have I overlooked something? There should be a DISABLE_NRLMSIS switch.

**Comment by alexmyczko** [comment]
So sorry, I did not expect that. Will try it…

**Comment by alexmyczko** [comment]
Thank you https://packages.debian.org/sid/groops now we just need to get rid of non-free

**Comment by alexmyczko** [comment]
ah licenses incompatibities, is there a way to fix it?

the IERS license is not compatible with GPL-3 and thus the GPL software can be only combined with the IERS software in case it is not modified.
This is ok for non-free.
But as the IERS license requires for example renaming of modified functions, this software can not be used together with GPL-software in main.

**Comment by tmayerguerr** [comment]
Same solution?: Compile with DISABLE_IERS.

**Comment by alexmyczko** [comment]
that worked, it's now part of non-free/groops...
