### ISSUE TITLE
question for the output of Kinematic orbit determination of LEO satellites

### ISSUE THREAD

**Issue by sustech-zpzeng** [groops-devs/groops#30]
HI, I followed the cookbook and I successfully ran the example scenario for Kinematic orbit determination of LEO satellites. I want to know why the output gracefo1_orbit_2020-01-01 is slightly different from the Index of  /outgoing/ITSG/satelliteOrbitProducts/operational/GRACEFO-1/kinematicOrbit/2020 in the same steps and under the same version conditions

**Comment by tmayerguerr** [comment]
GROOPS is continuously extended and improved. The operational orbits are calculated with the current internal developer version. Therefore, minor differences may occur.
