### ISSUE TITLE
question for cycle slips detection

### ISSUE THREAD

**Issue by gnssxx** [groops-devs/groops#31]
Hi, I'd like to consult you.  The first question is, in cycle slip detection, what are the advantages of adding total variational denoising algorithm in the MW-like combination method? I artificially added some cycle slips, which could not be detected, without understanding what the advantages are.  The second question is that the method based on geometry-free linear combination of complementarity also misses some cycle slips, so what is the significance of complementarity?  Thank you very much!

**Comment by tmayerguerr** [comment]
We are aware that our method for detecting cycle slips is not optimal at the moment. We intend to improve it in the future.

The denoising is necessary to reduce noise in some combinations and to avoid too many false positive cycle slip detections.
The geometry-free linear combination has to be checked additionally, because it is mathematically impossible to detect all linear combinations of cycle slips with the first method.

regards
Torsten

**Comment by gnssxx** [comment]
Thank you very much for your reply. I am a student at school. Your reply is very helpful to me.  

regards

**Comment by gnssxx** [comment]
Hello,


Can you provide me with the relevant theoretical formulas of MW combination and total variation denoising algorithm in the first method of cycle slip detection? It is mainly about how the MW combination value is combined. What value is output file in outputfiletrackbefore.


Because I don't understand the source code of this matrix calculation. Thank you!


regards
jj
| |
景鑫
|
|
***@***.***
|
On 1/13/2022 14:06，Torsten ***@***.***> wrote：

We are aware that our method for detecting cycle slips is not optimal at the moment. We intend to improve it in the future.

The denoising is necessary to reduce noise in some combinations and to avoid too many false positive cycle slip detections.
The geometry-free linear combination has to be checked additionally, because it is mathematically impossible to detect all linear combinations of cycle slips with the first method.

regards
Torsten

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
