### ISSUE TITLE
Reference Data for Deducing Orbit Differences and Station Statistics

### ISSUE THREAD

**Issue by GALATIYA** [groops-devs/groops#33]
Greetings GROOPS Developers,

Many thanks for the robust software.

My question may be too simple. However, I am just curious to know with respect to GROOPS. I am performing an experiment on GNSS orbit determination. I, therefore, wonder if you could advise me on how to get the reference **clocks**, **orbits**, and **station** data (such as **referenceTUG0R03FIN**, included in the **scenarioGnssNetwork**). In the case that I process data other than the one provided in this example, how can I get this data for comparison? 

Thanks for your usual support.

Regards,

Galatiya.

**Comment by sestras** [comment]
Hello Galatiya,

You can find our IGS repro3 products, which cover the years 1994-2020 and GPS, GLONASS, and Galileo, here: https://www.tugraz.at/institute/ifg/downloads/gnss-reprocessing-products/
You can also find these products along with products from other analysis centers in the IGS data centers: https://www.igs.org/products-access

As this has nothing to do with GROOPS itself, I'll close this issue.

Best regards,
Sebastian

**Comment by GALATIYA** [comment]
Greetings Sebastian,

This is noted with thanks. 

Regards,

Galatiya.
