### ISSUE TITLE
Some questions in debugging GROOPS and AR

### ISSUE THREAD

**Issue by FFFFFG-IGG** [groops-devs/groops#34]
Hello developers!
  I'm a c++ user of 'Visual Studio(VS)', recently I'm trying to modify the source codes of GROOPS and debug it in VS mode. But I'm confused about how to start. I have corresponded with Sebastian Strasser and he gave me an example of debugging GROOPS under 'VS Code'. However, 'VS Code' is not convenient for building a program directly. So could you give me some suggestions in debugging GROOPS in Visual studio? 
  By the way, I noticed that ambiguity resolution in GROOPS is solved by using "MLAMBDA" in the relative article.  Here, I wonder if there is a double-differential ambiguity step that MLAMBDA is used for AR in GROOPS network processing? Or MLAMBDA is implemented directly on the float ambiguity?
  Could you give some suggestions about these questions?
Many thanks!
Yongzhao Fan.

**Comment by akvas** [comment]
Dear Yongzhao Fan,

I am afraid that questions about your development environment go beyond the support we can offer. There is plenty of information available on how to set up Visual Studio. 

Details on the ambiguity resolution can be found in https://doi.org/10.1007/s00190-018-1223-2, section 3.4.

Regards,
Andreas

**Comment by lambert87041** [comment]
I have tried compile GROOPS using visual studio too. But it seems that Visual Studio does not support to compile FORTRAN files in mixed-Language solutions. However, the parts related to FORTRAN can be made into additional libraries. But after I tried, I found that this method still didn't work. In addition, there are many problems in compiling some third-party libraries, especially the NETCDF. If you solve these problems, I hope you can give me some help.

**Comment by zdwangjian5** [comment]
hello, have you solved this problem? i want to debug with vs, but i do not know how to do. how to debugging GROOPS under 'VS Code'?

**Comment by FFFFFG-IGG** [comment]
> 

I've debugged groops in vs code successfully(windows OS). You need make groops in the Debug mode and used gcc compiler to launch it in the vs code. Remember to give the path of .xml in the launch.json file.

**Comment by zdwangjian5** [comment]
Thank you! I have solved this problem with clion software.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "groops-devs/groops"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月28日(星期一) 下午2:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [groops-devs/groops] Some questions in debugging GROOPS and AR (Issue #34)





   
I've debugged groops in vs code successfully(windows OS). You need make groops in the Debug mode and used gcc compiler to launch it in the vs code. Remember to give the path of .xml in the launch.json file.
