### ISSUE TITLE
Issues when converting station coordinates from SINEX with program Sinex2StationPosition

### ISSUE THREAD

**Issue by Bemtgenj** [groops-devs/groops#35]
Hello,

I wanted to do some position studies with the Zim3 station, but could not find the /.../stationPosition.zim3.dat file to run the GNSS processing program (directory" C:\Users\121005051E\DATA\PhD Studies\Groops project\Data\gnss\receiverStation\position\igs\igsR3/ -  zimm and zim2 station position files are available in this directory). Am i looking in the wrong place / doing something wrong or is the file not available in the DATA set? the stationInfo.zim3.xml is available

TXS for the help

Best regards
Jean Bemtgen

**Comment by lambert87041** [comment]
Maybe you can try to convert the SINEX file with ZIM3 to the stationInfo files you need. The detailed steps could be found in the cookbook.

**Comment by Bemtgenj** [comment]
Hello 

small update - we have created a program (see attached) that uses Sinex2StationPosition to convert the data from "TUG0R03FIN_{loopTime:%y%03O}0000_01D_01D_CRD.SNX.gz files. What seems strange to us is when we define zim2 (run as baseline to check if the program works) and zim3 we get the same output file. I have attached the different files for easier understanding of what we did. The other idea which we had was to see compare the content of the GROOPS Data stationPositionzim2.dat file to "our" zim2 stationPosition file. but we have not been able to convert the dat file into a readable file. We noticed however for GROOPS data stationPositon.zim2.dat about 200kb and for our zim2 station position file about 1kb, so there must be something we are not doing correctly

thanks again in advance or the help
BR
Jean

[stationPosition364zim2.txt](https://github.com/groops-devs/groops/files/8169698/stationPosition364zim2.txt)
[stationPosition364zim3.txt](https://github.com/groops-devs/groops/files/8169701/stationPosition364zim3.txt)
[Positionzim2.zip](https://github.com/groops-devs/groops/files/8169705/Positionzim2.zip)

**Comment by Bemtgenj** [comment]
Hi Sebastian

txs much for the feedback and the help - much clearer now

Best regards
Jean

**Comment by parisaSHAFIEI** [comment]
Hi Sebastian, 

I hope you are doing well.

I have just a quick question about the station position. As a matter of fact, Jean and I ran the config file, i.e. Position.xml, and got the values for "zim2" which are slightly different among the two of us and the GROOPS station position baseline. For instance, I have attached the file that Jean and I got for 29 December 2020 for "zim2" station. It is strange for us to see the numbers are not exactly the same and comparing to the baseline they are also not the same. It should be noted that we have used the TUG SINEX products. Please see the attached files. 

Thank you in advance.

Cheers, 
Parisa 

[stationPosition_364_Parisa.zim2.txt](https://github.com/groops-devs/groops/files/8171354/stationPosition_364_Parisa.zim2.txt)

[stationPosition_364_Jean.zim2.txt](https://github.com/groops-devs/groops/files/8171362/stationPosition_364_Jean.zim2.txt)

[TUG0R03FIN_20203640000_01D_01D_CRD.SNX.gz](https://github.com/groops-devs/groops/files/8171365/TUG0R03FIN_20203640000_01D_01D_CRD.SNX.gz)

[stationPositionzim2.txt](https://github.com/groops-devs/groops/files/8171383/stationPositionzim2.txt)

**Comment by sestras** [comment]
Hi Parisa,

When I run the script locally, I get exactly the same output as you. Are you sure that Jean used exactly the same script and files? The coordinates in Jean's file differ by several meters, which I'm pretty sure cannot be caused by numerical issues, for example due to different computer platforms. In any case, which platforms are you using?

The "baseline" you are referring to are the igsR3 reference frame coordinates. They represent a linear movement (i.e., position+velocity) of the station, which differ from the estimated daily coordinates in the TUG0R03FIN SINEX files. These contain other signals (e.g., annual) and are also affected by noise. Therefore, they differ from the reference frame coordinates. The reference frame coordinates are only used to align the daily solutions to the IGS reference frame during processing using no-net rotation and translation constraints. 

Best regards,
Sebastian

**Comment by parisaSHAFIEI** [comment]
> 

Hi Sebastian, 

Thank you for your feedback. 

We ran it again and compared the values, i.e. x, y and z, for three days. Based on this comparison, we got the same output. I am not sure, but maybe something was missed in the first time that we ran the program. 

Thank you again for the time you spent on helping us.

Best regards,
Parisa
