### ISSUE TITLE
Is there something wrong in filegrace.cpp？

### ISSUE THREAD

**Issue by zdwangjian5** [groops-devs/groops#37]
hello , i want to use the graceL1A2Accelerometer.cpp to convert the l1a to instrument file, but when i use the "FileInGrace::flag(qualityFlag)", i find the qualityFlag does not return a byte value ,but a unknown value"?"，
my c++ is not very good, i  debug v is right , i do not know whether there is something wrong with below codes？
Looking for your reply,thanks!

 switch(x.size)
      {
        case 1 : *reinterpret_cast<Byte  *>(x.value) = v; break;
        case 2 : *reinterpret_cast<UInt16*>(x.value) = v; break;
        case 4 : *reinterpret_cast<UInt32*>(x.value) = v; break;
        case 8 : *reinterpret_cast<UInt64*>(x.value) = v; break;
        default:
          throw(Exception("something strange"));
      };

**Comment by tmayerguerr** [comment]
Could you provide me the complete error message and send me the actual ACC1A file that produces the error? I will have a look into it.
regards
Torsten

**Comment by zdwangjian5** [comment]
Thanks for your reply. The L1A file is downloaded  from 'ftp://isdcftp.gfz-potsdam.de/grace-fo/Level-1A/JPL/INSTRUMENT/RL04/2019'. And i used the 'ACC1A_2019-01-01_C_04.txt'.

the complete output is :
--- GraceL1A2Accelerometer (LRI\ACC) ---
read input files
read file <E:\ACC1A_2019-01-01_C_04.txt>
qualityFlag < >
prodFlag4 <?>
Accelerometer:
  arc count: 1
  epochs:    0
  gaps (> 0.2 s):  0
=== Finished GROOPS ===

**Comment by zdwangjian5** [comment]
can you help to take a look at this problem ? 
or can you tell me to how to debug with VS2019? I only how to run with msys2 ,but I donot how to debug this program with breakpoint？
when i open the sources with vs2019,there will be many errors due to the path of headfiles.my c++ is poor.

**Comment by tmayerguerr** [comment]
I am working at the problem. The GRACE conversion programs are a little bit chaotic and I try to refactor them and to eliminate the bugs.

**Comment by zdwangjian5** [comment]
Thank you very much!

**Comment by tmayerguerr** [comment]
New revised code for GRACE L1B/L1A data conversion is committed now.
The use of GRACE L1A data is still experimental and not completely useful. I recommend to use the L1B data.

**Comment by zdwangjian5** [comment]
Thank you very much!  The var "Byte   qualflg;" is still  < >. prodFlag is ok.
i wonder why the char is defined as these two ways in portable.h?
"typedef char              Byte;
typedef bool              Bool;
typedef char              Char;"

**Comment by tmayerguerr** [comment]
> The var "Byte qualflg;" is still < >. prodFlag is ok.

Is this your own debugging output?

c/c++ do not distinguish between a character and an integer with the size of a byte. We used the typedefs to indicate the different meanings in our source. For streams you must still tell the meaning:
~~~
  char c = '0'; // is ASCII number 48
  std:.cout<<"interpret as character: <<c<<std::endl;
  std::cout<<"interpret as number: <<int(c)<<std::endl;
~~~

**Comment by zdwangjian5** [comment]
You can close this issue.Thank you for your help!
