### ISSUE TITLE
how to ensure successful installation under Windows

### ISSUE THREAD

**Issue by mayifangyuan** [groops-devs/groops#4]
Hi, I've installed groops under Microsoft Windows 7 following the  installation guide. But I'm not sure that whether groops has been installed correctly.
So I'm wondering how to prove the successful installation under Windows.
Thanks.

**Comment by sestras** [comment]
Hello,

First of all, we have only tested GROOPS under Windows 10, so we cannot guarantee that everything works under Windows 7, although it might.

If you have installed GROOPS following the installation instructions (including the post-installation steps), there should be a executable file "groops.exe" in "C:\groops\bin" (or the installation path you chose). You should also be able to open a command line interface (Windows+R, cmd.exe) and just type in "groops.exe" (without "). The output should be similar to:

> === Starting GROOPS ===
Gravity Recovery Object Oriented Programming System (GROOPS)
Usage: groops [--log <logfile.txt>] [--settings <groopsDefaults.xml>] [--silent] [--global name=value] <configfile.xml>
       groops --write-settings <groopsDefaults.xml>
       groops --xsd <schemafile.xsd>
       groops --doc <documentation/>
 -h, --help           this text
 -l, --log            append messages to logfile. If a directory is given, one time-stamped logfile will be created inside for each groops script.
 -g, --global         pass a global variable to config files as name=value pair
 -c, --settings       read constants from file (default search: groopsDefaults.xml)
 -s, --silent         runs silently
 -d, --doc            generate documentation files (latex/html/...)
 -x, --xsd            write xsd-schema of xml-configfile options
 -C, --write-settings write the users current settings to file
GitHub repository: https://github.com/groops-devs/groops

If that is the case, then GROOPS has been successfully compiled.
