### ISSUE TITLE
Does groops run differently in windows and ubuntu?

### ISSUE THREAD

**Issue by FFFFFG-IGG** [groops-devs/groops#42]
Hello developers!
  Recently I've processed gnss data with 100 stations in network procedure on OS windows successfully. But when I deployed my project on the ubuntu, I found that groops only read first 66 lines of station name in stationlist.txt, which should be 100.  I'm sure the config file and data are exactly same. Could you give me some instrutions about this?
many  thanks!

**Comment by sestras** [comment]
Hello,

We cannot help you unless you provide more information (see [Contributing guidelines](https://github.com/groops-devs/groops/blob/main/CONTRIBUTING.md)). Please provide the station list file and the GROOPS config file. My first guess would be that your station list file might contain carriage returns, which could cause issues under Linux.

In principle, there should not be any differences between operating systems.

Best regards,
Sebastian

**Comment by FFFFFG-IGG** [comment]
> Hello,
> 
> We cannot help you unless you provide more information (see [Contributing guidelines](https://github.com/groops-devs/groops/blob/main/CONTRIBUTING.md)). Please provide the station list file and the GROOPS config file. My first guess would be that your station list file might contain carriage returns, which could cause issues under Linux.
> 
> In principle, there should not be any differences between operating systems.
> 
> Best regards, Sebastian

Here are my configfile and stationList file:
[config_stationList.zip](https://github.com/groops-devs/groops/files/8350484/config_stationList.zip)
I'm confused with "your station list file might contain carriage returns, which could cause issues under Linux", actually, without CR how can I arrange stationname by linewise? By the way, I also tried the LF mode(txt in unix), it doesn't work. What's worse, when I used the "stationList.repro3.core.tiered.txt" downloaded from itsg directly, the problem also existed.

**Comment by sestras** [comment]
Thanks. There does not seem to be anything wrong with the station list file from what I can tell. Windows uses carriage return and line feed (CRLF) while Linux only uses LF. But since your station list file does not contain carriage returns, this is not the source of the issue.

Can you please provide log files (`groops -l logfile.txt <config.xml>`) from running your script on both Windows and Linux? Maybe comparing the two can shed some light on what is going on.

**Comment by FFFFFG-IGG** [comment]
> Thanks. There does not seem to be anything wrong with the station list file from what I can tell. Windows uses carriage return and line feed (CRLF) while Linux only uses LF. But since your station list file does not contain carriage returns, this is not the source of the issue.
> 
> Can you please provide log files (`groops -l logfile.txt <config.xml>`) from running your script on both Windows and Linux? Maybe comparing the two can shed some light on what is going on.

Here is the configFile & stationList file & logfile，note that the problem appeared at 010groopsConvert.xml, not the configfile I pasted before, sorry for that! And I have read the logfiles of both Ubuntu and windows, finding no hints of the problem I met.
[config_stationList.zip](https://github.com/groops-devs/groops/files/8354564/config_stationList.zip)

**Comment by sestras** [comment]
I think you accidentally attached the same file as in your previous message. It does not contain the log files and the 010groopsConvert.xml config file.

**Comment by FFFFFG-IGG** [comment]
> I think you accidentally attached the same file as in your previous message. It does not contain the log files and the 010groopsConvert.xml config file.

sorry for that, Now the attachment is correct.
[config_stationlist_log.zip](https://github.com/groops-devs/groops/files/8363762/config_stationlist_log.zip)

**Comment by FFFFFG-IGG** [comment]
So wierd! I've test the configFile you attached, and this time groops only read first 44 lines of the stationList_test.txt on Ubuntu while read normally on Windows(testfiles are in the attachment). And I've no idea with this issue after hundreds of tests.
  I've also futher test groops by adding loopProgram 'A'(the one echoes station name) into loopProgram 'B'(base on timeInterval), and found A echoed first 66 lines of stationList.txt, I thought this may shed some light on this issue. By the way, thanks for your kind reply!
[3.29_testResults.zip](https://github.com/groops-devs/groops/files/8367613/3.29_testResults.zip)

**Comment by alexmyczko** [comment]
@FFFFFG-IGG just for the record, what ubuntu version you run on which architecture? you build groops yourself? just for the record...

**Comment by Waley04** [comment]
@alexmyczko, I observe the same mismatch in stationList looping between Ubuntu and Windows. While you are waiting for his response, I use Ubuntu 20.04.4 LTS (release 20.04).

**Comment by FFFFFG-IGG** [comment]
> just for the record, what ubuntu version you run on which architecture? you build groops yourself? just for the record...

I use Ubuntu 20.04, the same as Waley04.

**Comment by sestras** [comment]
@akvas was able to reproduce the issue in an Ubuntu VM. It seems that it only occurred with gcc 9, but not with 8 or 10+, which is why we never noticed it. During some code restructuring predating the public release of GROOPS, the initialization of the variable optionally limiting the maximum number of iterations accidentally got lost. 

The issue should be fixed with 77db5bf. Can you please pull the latest version and confirm that this resolved the issue on your end?

Thank you for the bug report and thanks to everyone for helping us pinpoint the issue!

**Comment by Waley04** [comment]
@sestras, Thanks for resolving this issue. I used the latest groops version, and the stationList looping between Ubuntu and Windows is now matching.

**Comment by FFFFFG-IGG** [comment]
> @akvas was able to reproduce the issue in an Ubuntu VM. It seems that it only occurred with gcc 9, but not with 8 or 10+, which is why we never noticed it. During some code restructuring predating the public release of GROOPS, the initialization of the variable optionally limiting the maximum number of iterations accidentally got lost.
> 
> The issue should be fixed with [77db5bf](https://github.com/groops-devs/groops/commit/77db5bf72ca7e8fa8fbd0a7cedbb4ed40e02448f). Can you please pull the latest version and confirm that this resolved the issue on your end?
> 
> Thank you for the bug report and thanks to everyone for helping us pinpoint the issue!

Thanks for your marvelous work! This issue is now totally resolved.
