### ISSUE TITLE
Cycle slip detection of MW combination

### ISSUE THREAD

**Issue by gnssxx** [groops-devs/groops#43]
### Description

Hello,

Can you provide me with the relevant theoretical formulas of MW combination and total variation denoising algorithm in the first method of cycle slip detection? It is mainly about how is the MW combination calculated. Could you describe it to me.
Because I don't understand the source code of this matrix calculation. Thank you!

regards
j

### GROOPS version

Release 2021-09-06

### Operating systems

- [ ] Linux
- [X] Windows
- [ ] macOS
- [ ] Other (please specify in the description)

**Comment by gnssxx** [comment]
OK，Thanks

**Comment by sestras** [comment]
My doctoral thesis is now available at https://doi.org/10.3217/978-3-85125-885-1. The details provided in Chapter 7.1 should hopefully answer your question.

**Comment by gnssxx** [comment]
> My doctoral thesis is now available at https://doi.org/10.3217/978-3-85125-885-1. The details provided in Chapter 7.1 should hopefully answer your question.

I'm very glad to receive your paper. Thank you very much!
