### ISSUE TITLE
Insight in UPD evaluation and AR of groops network

### ISSUE THREAD

**Issue by FFFFFG-IGG** [groops-devs/groops#46]
### Description

Hello developers, recently I have learned more deeply in UPD evaluation of groops network processing and the UPD products using in PPP scenario. According to article you have published, TUG get UPD and ambiguities by "setting the UPD parameters but not integer ambiguities in the first time UPD appear in a track, and integer ambiguities are set in following tracks" . Thus, the results of UPD and integer ambiguities can be described as:
![1650460606(1)](https://user-images.githubusercontent.com/59271400/164239241-680d0c9e-b0a9-41b7-9314-dd316dc36273.jpg)

Questions that confused me a lot are:
1.Apparently, UPDs solved by TUG method include part of ignored integer ambiguities. In this case, due to the sum of influences of ignored ambiguities in rec and trans is not certain integer, does corresponding integer ambituities in the following tracks have Integer feature for sure? If not, the MLAMBDA can not fix the ambiguity correctly.
2. When it comes to PPP, if I would fix the ambiguity with UPD products derived by groops, there comes a question: Transmitter UPDs contain part of ignored integer ambiguities, and this part of ambiguities are not same among all transmitter UPDs, which means that it can not be offset by single-differential between satellites. This will affected solution of ppp for sure because the observation equation minus not only real trans UPD but also part influences of ignored integer ambiguities.

Could you give me some deep insight in UPD evaluation of groops beyond the article you've published? Many thanks!  

### GROOPS version

main (latest commit)

### Operating systems

- [ ] Linux
- [X] Windows
- [ ] macOS
- [ ] Other (please specify in the description)

**Comment by sestras** [comment]
Hello,

The ambiguity and phase bias parametrizations as well as the ambiguity resolution approach implemented in GROOPS are described in much more detail in my doctoral thesis, which will be published at the end of next week or the week after. I'd ask you to please wait for that, as it will hopefully answer your questions. I'll post the link here once it is available.

Best regards,
Sebastian

**Comment by FFFFFG-IGG** [comment]
@sestras Thank you and looking forward to your reply！

**Comment by sestras** [comment]
My doctoral thesis is now available at https://doi.org/10.3217/978-3-85125-885-1. The details provided in Chapter 6.6 should hopefully answer your question.

**Comment by FFFFFG-IGG** [comment]
@sestras Congrats! It's really an epic work！Thanks a lot!
