### ISSUE TITLE
groops.exe Entry Point Not Found

### ISSUE THREAD

**Issue by Waley04** [groops-devs/groops#47]
### Description

Greetings GROOPS Developers,

I can successfully install the GROOPS software on my Dell Precision 7920 Tower (Intel Xeon Bronze 3204 Processor) workstation. However, when I call the software on the command line, I get "groops.exe Entry Point Not Found" as shown in the attachment. 

![groopsEntryPointNotFound](https://user-images.githubusercontent.com/101952777/165248400-c32e7cd5-9c4b-4b6e-bf87-5672b7e0090d.PNG)

You may also refer to the installation log file attached. 

[groopsInstallation.log](https://github.com/groops-devs/groops/files/8560946/groopsInstallation.log)

I guess that it could be a problem with my workstation because I do not encounter any problem with GROOPS on my other PC. The attachment below justifies this.

![groopsLastestVersion](https://user-images.githubusercontent.com/101952777/165250675-1bee9609-b818-4d44-94d7-e6be251ed691.PNG)

Some useful system files (such as .dll) are present on the PC. I, therefore, wonder if you could advise me on this matter. 

Thanks for your usual support.

Regards,

Waley.

### GROOPS version

main (latest commit)

### Operating systems

- [ ] Linux
- [X] Windows
- [ ] macOS
- [ ] Other (please specify in the description)

**Comment by Waley04** [comment]
Hi Patrick,

Many thanks for your prompt response.

**Environment variables:** groops was added to the path.
**Optional installations:** No optional installations were skipped - all the installation steps were followed on both PCs.

I have had so many installation attempts this month.  I can install the software on the workstation but it fails to work using the Windows terminal and Powershell. Rather, it works when I invoke it using Git on Windows, an example is shown below. 
 
![groopsUsingGit](https://user-images.githubusercontent.com/101952777/165268415-345af59c-ea5e-4d2c-b7b8-fd6908823f57.PNG)

I am not sure why.

Regards,

Waley.

**Comment by zhedumi** [comment]
Hi Waley,

I cannot reproduce the issue but since it works with the git-terminal (I presume that is what you mean with Git) and not with the others that something is broken int he environmental variables or registry of the libraries?


Regards,

Patrick

**Comment by Waley04** [comment]
Hi Patrick,

There is no problem. The most important issue is that I can now use the software with Git.

Thanks with regards,

Waley
