### ISSUE TITLE
About LEO orbit determination

### ISSUE THREAD

**Issue by TengNian** [groops-devs/groops#48]
### Description

Hello developers!
Can I set the apriori orbit to 0 when performing LEO orbit determination?

### Operating systems

- [ ] Linux
- [X] Windows
- [ ] macOS
- [ ] Other (please specify in the description)

**Comment by tmayerguerr** [comment]
Dear TengNian,
No, you need an apriori orbit. Maybe you can use [SimulateKeplerOrbit](https://groops-devs.github.io/groops/html/SimulateKeplerOrbit.html) to create a very coarse orbit, but without guarantee that this is sufficient.
regards
Torsten
