### ISSUE TITLE
What is the refernce frame for processed LEO kinematic positions? 

### ISSUE THREAD

**Issue by ParisaShafiei** [groops-devs/groops#49]
### Description

Dear all, 

I have processed kinematic orbits for Sentinel 1A from 15 January 2022 to 25 January 2022 and now for validations, I want to compare the obtained kinematic orbits with another source of POD Data for instance with AIUB results. However, there is one important issue that the GROOPS kinematic orbits are totally different with AIUB results. Even, I have compared the Sentinel 1A POD results from TUG webpage with the AIUB orbits and they are also different form each other. Please look at the files, I have provided for you. 

So, I am just wondering that these differences might be because of the different reference systems. If it is the case, in which reference frame are the GROOPS orbits estimated? 

Thank you in advance and I am looking forward to hearing from you as soon as possible. 

Best regards, 
Parisa 

![AIUB-Sentinel1A](https://user-images.githubusercontent.com/99748448/167808611-7368d98c-8d0e-4dde-a4c2-9808e5863784.PNG)

![GROOPS_Sentinel1A](https://user-images.githubusercontent.com/99748448/167808963-f6d8c2b6-2730-4880-8ba1-b572e35a9434.PNG)

![AIUB](https://user-images.githubusercontent.com/99748448/167809201-5614024c-e150-4f82-869c-1b31ed361e54.PNG)

### Operating systems

- [X] Linux
- [X] Windows
- [ ] macOS
- [ ] Other (please specify in the description)

**Comment by tmayerguerr** [comment]
Dear Parisa,
Our orbits are given in a space fixed reference frame (ICRF)
whereas the AIUB orbits are provided in an Earth fixed frame (ITRF 2014/IGS14). 
This might explain the large difference.
regards
Torsten

**Comment by parisaSHAFIEI** [comment]
Dear Prof. Dr. Mayer, 

First of all, I want to appreciate the time you spent on answering my question.

Now, it is totally understandable why there are large differences between GROOPS processed orbits and the AIUB orbits. 

I also would like to ask another question about the apriori orbits which have been used in the processing. For instance, for Sentinel 1A mission, according to the ESA webpage, there are three types of orbits with different accuracy from 1m to 10cm and 5cm. In processing, I have used the POE orbits which are in 5 cm level as the apriori orbit in the software. Therefore, how do we can make sure what accuracy is required for the apriori orbits to do POD? And what are the orbits have been used for Sentinel 1A mission in Graz University of Technology to obtain those results? 

Please see the attachments in which I have provided you with the scenario that I have used for Sentinel 1A kinematic orbit determination. Could you please find it possible to provide us, as the GROOPS users, with simple example scenarios for such important missions which can help us learn more about the both the required inputs and the associated accuracy?

Thank you in advance for your cooperation and support and I am looking forward to hearing from you as soon as possible. 

Best regards, 

Parisa 

[Sentinel 1A.zip](https://github.com/groops-devs/groops/files/8833379/Sentinel.1A.zip)

**Comment by ParisaShafiei** [comment]
Dear all, 

Regarding my previous question about the Sentinel 1A mission, my colleague and I have tried two different orbits from **https://scihub.copernicus.eu/gnss/#/home** as the apriori orbits in POD . Firstly, we used the Non Time Critical (NTC) products known as **AUX_POE ORB** and their accuracy is in 5 com range. For these products, we notice that each file only contains 1 hour data for each day. For instance the orbit for 15 January 2020 only contained 1 hour data for that day and the rest were inside next orbit file, i.e. for 16 January 2020, which showed that we have to introduce those files as input in GROOPS to get the proper kinematic positions. Secondly, since we could not find a solution for this problem, we decided to use another product as the apriori orbit for processing. Therefore, for the second attempt, we utilized the Near Real Time (NRT) products known as **AUX_PRE ORB** which their accuracy is in 1m. However, when we used these products, they final estimated kinematic orbits were so far from the ones available on the Graz University ftp webpage. 

Now, we are really stuck in reprocessing the kinematic orbits for this mission. In fact, our purpose is to learning by doing the important concepts included in GROOPS. Therefore, since you have reprocessed these orbits, we would be really pleased if you could let us know how you solve this problem or if we have used the right products or not. 

Thank you in advance for your cooperation and support. 

I am looking forward to hearing from you as soon as possible. 

With Best Wishes, 
Parisa

**Comment by bsuesser-rechberger** [comment]
Dear Parisa, 

yes, we use the AUX_POEORB data from Copernicus. For example: 15.01.2020 data is stored in the file S1A_OPER_AUX_POEORB_OPOD_20210316T225001_V20200114T225942_20200116T005942.zip.  (with one hour overlap with the day before and day after).

Best regards, 
Barbara
