### ISSUE TITLE
An example for groops users under Windows

### ISSUE THREAD

**Issue by mayifangyuan** [groops-devs/groops#5]
Hi, Could you provide an simple example for the use of groops under windows to help me learn this software?

Thanks.

**Comment by sestras** [comment]
Hello,

Attached you can find an archive containing an example GROOPS config file (example.xml) that simply integrates a Kepler orbit and writes the output to a file (orbit.txt). The archive also includes an example log file (logFile.txt) from running the config file.

If you run the example config file in a Windows command line terminal as
`groops.exe --log myLogFile.txt example.xml`
it should create a file orbit.txt in the same directory as example.xml that you can compare to the one provided in the archive. The contents of file myLogFile.txt should also match those of the provided logFile.txt.

You can also run the example config file directly from the GUI in case you have installed it (which I recommend). For details on that please see the documentation here: https://groops-devs.github.io/groops/html/general.gui.html

The [documentation](https://groops-devs.github.io/groops/html/index.html) also contains chapters with general information about GROOPS and how to use it.

[example.zip](https://github.com/groops-devs/groops/files/6221983/example.zip)
