### ISSUE TITLE
How to concatenate instrument file on the column level?

### ISSUE THREAD

**Issue by FFFFFG-IGG** [groops-devs/groops#52]
### Description

Hello, developers!
    I'd like to calculate the rms between the ppp results(position) and the IGS sinex solutions, and then plot them with plotGraph. However, it seems that plotGraph can only process matrix by column, and only one input is accessible. 
     For above reasons, I'd like to combine the snx position and the ppp results on the column level(add the snx positons at the right side of the ppp result file epoch wise),which can be further processed in plotGraph(for rms calculation). And I've tried InstrumentConcatenate and found it can only combine the row of multiple files, which can not reach my purpose. 
    So could you give me some suggestion for concatenate files on the column level by using groops?(or some clues of calculating rms between ppp results and IGS sinex position)?
Many thanks!

### Operating systems

- [ ] Linux
- [X] Windows
- [ ] macOS
- [ ] Other (please specify in the description)

**Comment by tmayerguerr** [comment]
You can use [InstrumentArcCalculate](https://groops-devs.github.io/groops/html/InstrumentArcCalculate.html) (or FunctionsCalculate) for this task.
regards
Torsten

**Comment by FFFFFG-IGG** [comment]
> You can use [InstrumentArcCalculate](https://groops-devs.github.io/groops/html/InstrumentArcCalculate.html) (or FunctionsCalculate) for this task. regards Torsten

TXS for the help. But here comes a new question:I'd like to combine the snx position(instrument file resampled with 2880 epochs) with the ppp result(<=2880 epochs) on the column level. To execute the 'instrumentArcCalculate', the instrumentSynchronize need to be run first(make sure that their row number are the same), however, I found the time tag of epoch of ppp result and that of snx postion are not exact same(or differ a lot), which may lead the 'instrumentSynchronize' run in the wrong way. What should I do to synchronize the snx position instrument file and ppp result instrument file to may sure they have the same number of rows?

**Comment by zhedumi** [comment]
You could use [Sinex2StationPosition](https://groops-devs.github.io/groops/html/Sinex2StationPosition.html) and within the [timeSeries](https://groops-devs.github.io/groops/html/timeSeriesType.html) option provide the ppp instrument file to create snx positions at already correct epochs which then can be easily columnwise merged with [InstrumentArcCalculate](https://groops-devs.github.io/groops/html/InstrumentArcCalculate.html).
Another options is to adjust the margin within [InstrumentSynchronize](https://groops-devs.github.io/groops/html/InstrumentSynchronize.html)

**Comment by FFFFFG-IGG** [comment]
> You could use [Sinex2StationPosition](https://groops-devs.github.io/groops/html/Sinex2StationPosition.html) and within the [timeSeries](https://groops-devs.github.io/groops/html/timeSeriesType.html) option provide the ppp instrument file to create snx positions at already correct epochs which then can be easily columnwise merged with [InstrumentArcCalculate](https://groops-devs.github.io/groops/html/InstrumentArcCalculate.html). Another options is to adjust the margin within [InstrumentSynchronize](https://groops-devs.github.io/groops/html/InstrumentSynchronize.html)

Thanks for you feedback!One more question, how can I concatenate multiple files in a convenient way(for example, concatenate years of instrument file)? Many thanks!!!

**Comment by zhedumi** [comment]
You can use [InstrumentConcatenate](https://groops-devs.github.io/groops/html/InstrumentConcatenate.html) as an example. Checkout issue #36 which has an elaborate explanation on how todo that.

**Comment by FFFFFG-IGG** [comment]
> 
Thanks, and I have sovled this problem.
