### ISSUE TITLE
GROOPS in WSL environment

### ISSUE THREAD

**Issue by Bemtgenj** [groops-devs/groops#57]
### Description

I have installed GROOPS in th windows WSL environment and when i execute groopsGUI i get the fllowing error mesage

jeanbemtgen@PP0268:~/groops/bin$ ./groopsGui
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

I reinstalled: sudo apt-get install --reinstall libxcb-xinerama0, but get same error message 

TXS for the help

BR
Jean

### Operating systems

- [ ] Linux
- [X] Windows
- [ ] macOS
- [ ] Other (please specify in the description)

**Comment by sestras** [comment]
Hi Jean,

Which version of Windows are you using? WSL only supports Linux GUI programs starting with Windows 11 Build 22000 or later (see https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps). WSL on Windows 10 only supports command line programs. I have not tried using the GROOPS GUI via WSL on Windows 11 yet, so I cannot provide any helps or tips. 

What I've tried is installing GROOPS via Win10 WSL and installing the GUI natively on Windows. It worked surprisingly well at first, however, I quickly ran into issues with the different handling of paths in Windows and Linux. There are some workarounds and WSL offers some tools for path conversion, but in the short time I spend on testing this, I did not end up with a fully satisfactory solution.

If you find a convenient solution or get the GUI working via WSL on Win11, please post your solution here so it might help others.

Best regards,
Sebastian

**Comment by Bemtgenj** [comment]
Hi Sebastian
txs for the feedback.

I am using windows 10 enterprise. I installed 2 version of GROOPS on my PC (GROOPS and GROOPS GUI / QT in the native Windows environment - this works fine, no problem and then GROOPS / GUI in the WSL environment and this is were I get the above error message) If I understood your message correctly that it is would normal to get the error message with the Windows 10 version. 

BR
Jean

**Comment by sestras** [comment]
Yes, WSL on Windows 10 does not support Linux graphical user interfaces.
