### ISSUE TITLE
Vienna mapping

### ISSUE THREAD

**Issue by Bemtgenj** [groops-devs/groops#58]
### Description

Hello,

I am planning to run station PPP from 2006 to 2021 and GROOPS itself provides vmf data for 2020 to 2022. Based on the link that is given in the GROOPS document (Gridded VMF data is available at: https://vmf.geo.tuwien.ac.at/trop_products/GRID/) i checked the TU Vienna web site. but i am not sure sure which vmf directory was used in the GROOPS troposphere data set - 1x1 grid vmf3.OP? What would be the corresponding data set for 2006 until 2019 then? The different vmf3 data sets do not have data for every year and i have not yet been able to find corresponding documentation on the differences in the sets except maybe for the "model" for the vmf files. I want to make sure i stay consistent with the vmf input data files.

Txs for the help

BR
Jean. 

### Operating systems

- [ ] Linux
- [X] Windows
- [ ] macOS
- [ ] Other (please specify in the description)

**Comment by sestras** [comment]
Hi Jean,

The VMF3 data set we provide on our FTP server is converted from https://vmf.geo.tuwien.ac.at/trop_products/GRID/1x1/V3GR/V3GR_OP/ (VMF3 + gradients, 1x1°, operational products). The operational data goes back to 2008, so before that you have to use the ERA-Interim reprocessed products (https://vmf.geo.tuwien.ac.at/trop_products/GRID/1x1/V3GR/V3GR_EI/). This series has been consistently reprocessed over a long time span, but stops in 2019.

You can find a list of relevant publications and some documentation on the VMF models here: https://vmf.geo.tuwien.ac.at/

Best regards,
Sebastian

**Comment by Bemtgenj** [comment]
HI Sebastian,

Txs for the quick feedback. This is confirming what i was thinking GROOPS was using. I guess my next step now is to figure out to convert the TU Vienna vmf3 / V3GR data for all those years so that it can be used in GROOPS as an input file. I assume the conversion can be done in GROOPS? or did you use some other method?

MfG
Jean

**Comment by Bemtgenj** [comment]
through the ViennaMappingFunctionGrid2File program

**Comment by Bemtgenj** [comment]
Hi Sebastian

I have been trying to convert the vmf file with the GROOPS - ViennaMappingFuncionGrrid2File Program but i am running into a time count problem (Viennamapping.xml). In a second config file that i was trying out I put a loop on the input file that keeps the input file open and with that the program was running , but i am not sure this is a correct logic  (attached file viennamappingtest.xml). Would you have an example of how it should be done - that i could take a look at? To save time in the programming phase i am not running an entire year yet, only 1 month+ (once i get he program working then i will run it for all the years

maybe a bit of background:  We have about 5 (maybe 6 depending on the time frame) GNSS stations here in Luxembourg (not part of IGS network) and we want to do PPP for these stations from 2006 until 2021. This why we need the VMF files for those other years for now and then from what i saw in the next step is defining the station position.

TXS for the help

BR
Jean

[ViennaMapTest.txt](https://github.com/groops-devs/groops/files/8906615/ViennaMapTest.txt)
[ViennaMap.txt](https://github.com/groops-devs/groops/files/8906616/ViennaMap.txt)
[Case_Study_Lux_Jun22.zip](https://github.com/groops-devs/groops/files/8906669/Case_Study_Lux_Jun22.zip)

**Comment by sestras** [comment]
Hi Jean,

Here is an example script for converting VMF3 data: [01groopsConvertVmf3.xml.gz](https://github.com/groops-devs/groops/files/8950034/01groopsConvertVmf3.xml.gz). It contains two variants (ERA-Interim, operational). Both use the 1x1° V3GR (delays + gradients) data sets you can download from website linked above. The script creates monthly files over the time span defined by the global variables `timeStart` and `timeEnd`.

Hope this helps,
Sebastian

**Comment by sestras** [comment]
I'm planning to record some tutorial videos on basic GROOPS features and usage soon, which will hopefully help with issues such as this.

**Comment by Bemtgenj** [comment]
Perfect, Parisa and i will be for sure watching them
