### ISSUE TITLE
the ftp cannot open,what is wrong with it?

### ISSUE THREAD

**Issue by zdwangjian** [groops-devs/groops#6]
the ftp (ftp://ftp.tugraz.at/outgoing/ITSG/groops/data)cannot open,what is wrong with it? 
Can you send the ftp data to my email 363127921@qq.com? thank you very much.

**Comment by akvas** [comment]
The links to the FTP server in the cookbook are updated in 7f848ff9f1bff8467d430ae9d0b8bcc7cbaf959c and should be accessible by web browser.

Cheers,
Andreas
