### ISSUE TITLE
Station position file (not part of IGS network

### ISSUE THREAD

**Issue by Bemtgenj** [groops-devs/groops#60]
### Description

Hello

As mentioned  before we are currently doing PPP for the stations here in Luxembourg. Unfortunately these stations are not part of the IGS network and hence not in the GROOPS baseline. Do you have any advice on how to create the following time series file {groopsDataDir}/gnss/receiverStation/position/igs/igsR3/stationPosition.{station}.dat for those specific stations? i saw a script Sinex2StationPosition, but i am not sure there are SINEX files available in case this script could be used

Thank you very much for your help

BR
Jean

### Operating systems

- [ ] Linux
- [X] Windows
- [ ] macOS
- [ ] Other (please specify in the description)

**Comment by FFFFFG-IGG** [comment]
> 

Hello, what do you want to do with stationPosition.dat?Since PPP does not need this file. By the way, script Sinex2StationPosition can extract station position form Weekly solution(snx), this is usually used to deal with IGS station, as far as I know. If you just want to do PPP, you may not need stationPosition.dat, if not, you can get the precise postion from other ways.

**Comment by Waley04** [comment]
Hi,

For none IGS stations, I guess one way of including information for such stations could be using the following: [GnssReceiverDefinitionCreate](https://groops-devs.github.io/groops/html/fileFormat_gnssReceiverDefinition.html), [GnssStationLog2StationInfo](https://groops-devs.github.io/groops/html/GnssStationLog2StationInfo.html) or GnssStationInfoCreate[https://groops-devs.github.io/groops/html/GnssStationInfoCreate.html](url).

**Comment by Bemtgenj** [comment]
Quick update

i looked through the 3 script files and noted that none of them create a time series with x,y,z positions which is what the *stationPosition.{station}.dat is from what i saw by opening the file for another station. I did actually use the GNSSStationLog2StationInfo to create a stationInfo.basl.xml file from the station information i had (for now i called the Bascharage station basl until i have found the proper name).  

Cheers
Jean


[Case_Study_Lux_Jun22.zip](https://github.com/groops-devs/groops/files/8990251/Case_Study_Lux_Jun22.zip)
)

**Comment by sestras** [comment]
Hello,

As has already been mentioned, the stationPosition file is optional and not required for PPP. The stationInfo file, which you can generate from a station log file, should already contain an approximate position of the station. As long as this is somewhat correct (i.e. <100 m), this is sufficient. The option to read a separate stationPosition file is only there for other applications, for example if you want to use a fixed station network to estimate satellite orbits.

**Comment by Bemtgenj** [comment]
Hi Sebastian,
Txs for the feedback.

i get it now - as there is no red star on the input file line it is not absolutely needed to run the GNSS processing. My stationInfo file does have x,y,z defined, so i should be good to run the script. I just need to check again if there is any other specific station file that is needed, last time i checked i did not see any other file needed.

Txs for the help

Cheers
Jean

**Comment by Bemtgenj** [comment]
Hello

I removed that input as suggested and the script ran fine. ( I have some strange z position movement, but i think that has nothing to do with the script itself)

Txs again for the help

Cheers
Jean
