### ISSUE TITLE
How to disable parameter STEC? 

### ISSUE THREAD

**Issue by FFFFFG-IGG** [groops-devs/groops#61]
### Description

Hello developers!
  Since I just want to get station postion but STEC take a large space in the normal equations(NEQ), and I would like not to estimate STEC in NEQ and get a IF -like NEQ to improve efficiency. What should I do?(not set STEC VTEC and TECbiases in the parametrization or disable them in the processingStep?)

### Operating systems

- [ ] Linux
- [X] Windows
- [ ] macOS
- [ ] Other (please specify in the description)

**Comment by sestras** [comment]
Hello,

The STEC parameters are preeliminated from the normal equation system, thus they do not take up space in the normal equations. I assume you mean the VTEC parameters, which are set up at each epoch for each station and thus require quite a bit of memory for the normal equations.

There are two solutions:
1. If you do not care about outputting meaningful signal biases, you can just remove the parametrizations for [VTEC](https://groops-devs.github.io/groops/html/gnssParametrizationType.html#ionosphereVTEC) and [TEC biases](https://groops-devs.github.io/groops/html/gnssParametrizationType.html#tecBiases) and only leave the [STEC parametrization](https://groops-devs.github.io/groops/html/gnssParametrizationType.html#ionosphereSTEC). Be sure to set `sigmaSTEC=0` in this case to estimate unconstrained STEC parameters.
2. You can also add a processing step [selectNormalsBlockStructure](https://groops-devs.github.io/groops/html/gnssProcessingStepType.html#selectNormalsBlockStructure) at the beginning of your steps in GnssProcessing with the setting `keepEpochNormalsInMemory=no`. This way, all epoch parameters (clocks, VTEC, TEC biases) are directly eliminated from the normal equations, which reduces the required amount of memory.

**Comment by FFFFFG-IGG** [comment]
> Hello,
> 
> The STEC parameters are preeliminated from the normal equation system, thus they do not take up space in the normal equations. I assume you mean the VTEC parameters, which are set up at each epoch for each station and thus require quite a bit of memory for the normal equations.
> 
> There are two solutions:
> 
> 1. If you do not care about outputting meaningful signal biases, you can just remove the parametrizations for [VTEC](https://groops-devs.github.io/groops/html/gnssParametrizationType.html#ionosphereVTEC) and [TEC biases](https://groops-devs.github.io/groops/html/gnssParametrizationType.html#tecBiases) and only leave the [STEC parametrization](https://groops-devs.github.io/groops/html/gnssParametrizationType.html#ionosphereSTEC). Be sure to set `sigmaSTEC=0` in this case to estimate unconstrained STEC parameters.
> 2. You can also add a processing step [selectNormalsBlockStructure](https://groops-devs.github.io/groops/html/gnssProcessingStepType.html#selectNormalsBlockStructure) at the beginning of your steps in GnssProcessing with the setting `keepEpochNormalsInMemory=no`. This way, all epoch parameters (clocks, VTEC, TEC biases) are directly eliminated from the normal equations, which reduces the required amount of memory.

Thanks for your feedback. I've solved my question.
