### ISSUE TITLE
fail to implement the first example of 'Instrument data handling' cookbook

### ISSUE THREAD

**Issue by bedbug6404** [groops-devs/groops#8]
Hi, 

Thank you for making the program open source

I am following the cookbook `https://groops-devs.github.io/groops/html/cookbook.instrument.html` to learn about the software. But I have difficulty to just start the first step

           Create three successively daily sinusoidal signals with TimeSeriesCreate

Attached is a snapshot of my input/program setting. But how can I make it a 'sinusoidal signal'? By doing what I posted, I can only get a file with only mJD time from **TimeSeriesCreate**. And the second program pops errors.

Thanks

![image](https://user-images.githubusercontent.com/31864183/122473959-8c3d4d00-cf90-11eb-8e18-76e90ac200ec.png)

**Comment by tmayerguerr** [comment]
Hi,

By default TimeSeriesCreate creates only one column with time (MJD) but you can add additional data columns.
In this data field mathematical expressions are allowed (see [parser](https://groops-devs.github.io/groops/html/general.parser.html)). The variable 'epoch' is filled with the MJD time for each time step. To create a sin with a period of 0.3 days add a data field and fill it with 'sin(2\*pi/0.3\*epoch)'.

regards
Torsten
