### ISSUE TITLE
format conversion problem

### ISSUE THREAD

**Issue by sunnday1** [groops-devs/groops#86]
Hello developer, I want to use the motion track output by Bernese as the prior track of GROOPS. Is this possible? I'm having a problem with the file conversion process, what's wrong with the settings in the image below? thank you very much！

![image](https://user-images.githubusercontent.com/95749295/182572966-5ba3d197-f68c-45dd-ad16-2ed005623bb7.png)

**Comment by zhedumi** [comment]
Hi,

Can you provide the output of the program in the form of the logfile or a screenshot? Can you also the data you try to convert?


Best regards,

Patrick

**Comment by sunnday1** [comment]
Thanks for taking the time to answer my question. Below is an addition to this question.
![image](https://user-images.githubusercontent.com/95749295/182745637-e7296669-15fe-48d2-812e-dc914637e77e.png)

[RDAF200010.txt](https://github.com/groops-devs/groops/files/9256075/RDAF200010.txt)

The file is the source file to be converted.

**Comment by sunnday1** [comment]
I successfully formatted the above file using the Sp3Format2Orbit program, but there was a problem with kinematic orbiting.
![image](https://user-images.githubusercontent.com/95749295/182753774-848d3996-fba4-456a-b0cd-3e1d1c4fa093.png)
![image](https://user-images.githubusercontent.com/95749295/182754089-5be1d40a-031a-4200-a2ea-f83068983573.png)

**Comment by akvas** [comment]
Hi @sunnday1,

it seems that the file "RDA.txt" is corrupted. Could you post it so we can verify that the conversion was correct?

Cheers,
Andreas

**Comment by sunnday1** [comment]
> 

[RDAF200010 .txt](https://github.com/groops-devs/groops/files/9482474/RDAF200010.txt)

**Comment by tmayerguerr** [comment]
This is the original SP3 file, not the converted one into GROOPS format (RDA.txt).
We see no problems to convert the sp3 file, see 
[example.zip](https://github.com/groops-devs/groops/files/9482816/example.zip)

**Comment by sunnday1** [comment]
Thank you so much for your example program, it helped us a lot, kudos to you all！

**Comment by sunnday1** [comment]
Thank you so much for your example program, it helped us a lot, kudos to you all！
