### ISSUE TITLE
Set the color of line plot

### ISSUE THREAD

**Issue by bedbug6404** [groops-devs/groops#9]
Hi, 

Following the second example of 'data handling', I reached the last step.  Then I hope to plot the result with different colors. However, it always comes out as black. 
As written [here](https://groops-devs.github.io/groops/html/plotColorType.html), I thought I could just file the **valueZ** with color (eg red) or three number as rgb (eg. 10 0 100) to have a color plot?

Attached are my inputs. 

PS: I guess, a screenshot like this would be super helpful for beginners to get familiar with the program. ^_^

![image](https://user-images.githubusercontent.com/31864183/122815235-2f4cda00-d2a3-11eb-9281-cf1b3ceae601.png)

**Comment by tmayerguerr** [comment]
Hi,

The color selector you are referring to is hidden in the line selector.
You can add additional symbols like circles and stars with different color (inside symbol).
If the color of the symbol should depend on the data you can choose a data column with valueZ (e.g. data2 or 100*data2), and add a colorbar in plotGraph to translate the value of each row into a color,
see [LinesAndPoints](https://groops-devs.github.io/groops/html/plotGraphLayerType.html).

I know our software is not easy to use and our documentation is not perfect, but we are scientists in a small research group and we are doing this alongside our normal work. Nevertheless we are currently discussing to offer an online course or additional YouTube tutorials, but this has not yet been determined.

regards
Torsten

**Comment by bedbug6404** [comment]
Thanks! Yeah, that's already a lot to make it open source.

Is there any way I can help? Say I upload those input setting screenshots of examples somewhere, as I am following the cookbook to learn the software right now.

**Comment by tmayerguerr** [comment]
Help from your side to improve the documentation is highly appreciated.
A good way is to commit the changes in your fork and make a pull request.

The documentation is written in latex and mostly directly included in the relevant source code.
- All figures are stored in C:\groops\docs\figures
- general texts and cookbooks are in C:\groops\docs\latex
  (see here for examples of the macros using to link to config elements or programs or to include graphics).
- the macro for figures is \fig{position}{width as fraction of textwidth}{filename}{label}{caption}

If you changes the latex content you must run groops in a terminal with the doc option:
  > groops.exe --doc C:\groops\docs

It generates additional *.auto.tex in the latex directory and all html files in the html directory.
If you would like to change the documentation in the sources you must build/compile before running groops.

If you open C:\groops\docs\documentation.html with a browser you should see the changes.

Thank you very much
regards
Torsten

**Comment by bedbug6404** [comment]
Thanks. I’ll try to do that. 

 

 

Best regard,

Chaoyang Zhang
